# Generated by Django 4.1.4 on 2022-12-22 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.activity'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='uploads/images'),
        ),
    ]
