# Generated by Django 4.1.4 on 2022-12-23 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_remove_image_section_activity_img_array'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='img_array',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='backend.image'),
        ),
    ]
