# Generated by Django 4.1.4 on 2022-12-23 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_alter_activity_img_array'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='img_array',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='backend.image'),
        ),
    ]
