# Generated by Django 4.1.4 on 2022-12-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_alter_activity_img_array'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='img_array',
        ),
        migrations.AddField(
            model_name='activity',
            name='img_array',
            field=models.ManyToManyField(to='backend.image'),
        ),
    ]
