# Generated by Django 4.1.4 on 2022-12-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
