# Generated by Django 4.1.4 on 2022-12-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_alter_activity_main_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='img_array',
        ),
        migrations.AddField(
            model_name='activity',
            name='img_array',
            field=models.JSONField(default='None'),
        ),
    ]
