# Generated by Django 4.1.4 on 2022-12-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_remove_activity_img_array_activity_img_array'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='img_array',
        ),
        migrations.AddField(
            model_name='activity',
            name='img_array',
            field=models.ManyToManyField(blank=True, related_name='activities', to='backend.image'),
        ),
    ]
