# Generated by Django 4.1.4 on 2022-12-31 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_remove_activity_img_array_activity_img_array'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='main_img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.image'),
        ),
    ]
