# Generated by Django 4.1.4 on 2023-01-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_activity_vid_array'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audio')),
                ('title', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
