# Generated by Django 4.1.4 on 2023-01-03 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_activity_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
