# Generated by Django 4.1.4 on 2023-01-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_alter_activity_img_array_alter_activity_main_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='vid_array',
            field=models.ManyToManyField(blank=True, default='none', related_name='videos', to='backend.video'),
        ),
    ]
