# Generated by Django 4.1.4 on 2023-01-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_alter_activity_vid_array'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='vid_array',
            field=models.ManyToManyField(blank=True, related_name='videos', to='backend.video'),
        ),
    ]
