# Generated by Django 4.1.4 on 2023-01-08 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
