# Generated by Django 4.1.4 on 2023-01-08 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='doc_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doc', to='backend.file'),
        ),
        migrations.AddField(
            model_name='production',
            name='pdf_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pdf', to='backend.file'),
        ),
    ]
