# Generated by Django 4.1.4 on 2023-01-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0053_production_doc_file_production_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='doc_file',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='production',
            name='pdf_file',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
