# Generated by Django 4.1.4 on 2023-01-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0055_production_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='production',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
