# Generated by Django 4.1.5 on 2023-01-16 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0056_activity_active_alter_production_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.audio'),
        ),
    ]
