# Generated by Django 4.1.5 on 2023-01-16 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0058_alter_activity_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.audio'),
        ),
    ]
