# Generated by Django 4.1.5 on 2023-01-17 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0060_alter_production_doc_file_alter_production_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='doc_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doc', to='backend.file'),
        ),
        migrations.AlterField(
            model_name='production',
            name='pdf_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pdf', to='backend.file'),
        ),
    ]
