# Generated by Django 4.1.5 on 2023-01-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0061_alter_production_doc_file_alter_production_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(blank=True, choices=[('doc', 'doc'), ('pdf', 'pdf')], max_length=10),
        ),
    ]
