# Generated by Django 4.1.7 on 2023-04-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0063_pbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbook',
            name='century',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pbook',
            name='crate',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pbook',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='pbook',
            name='edition',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pbook',
            name='investigator',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pbook',
            name='language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pbook',
            name='pdate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pbook',
            name='phouse',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pbook',
            name='publisher',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pbook',
            name='shelf',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pbook',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pbook',
            name='translator',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='pbook',
            name='author',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='pbook',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
