# Generated by Django 4.1.7 on 2023-05-05 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0068_remove_article_page_page_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='backend.page'),
        ),
    ]
